# Generated by Django 2.2.9 on 2020-01-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200119_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='category_field_id',
        ),
    ]
