# Generated by Django 2.2.9 on 2020-01-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200119_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_field_id',
            new_name='category_id',
        ),
    ]
